#!/bin/bash
gap=1

#Run our NUSPoly 
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 1 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 2 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 6 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 10 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 14 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 18 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 21 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 27 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 34 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 38 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 44 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 51 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 54 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 55 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 56 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 66 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 72 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 81 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 88 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 92 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 97 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 98 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True

# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 1 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 2 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 6 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 10 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 14 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 18 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 21 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 27 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 34 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 38 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 44 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 51 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 54 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 55 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 56 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 66 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 72 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 81 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 88 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 92 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 97 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True
# timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 98 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/cifar_relu_9_200.onnx --dataset cifar10 --epsilon 0.0011 --is_refinement True

timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 1 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 3 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 5 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 6 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 7 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 8 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 10 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 11 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 12 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 16 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 21 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 23 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 27 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 28 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 29 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 30 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 34 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 38 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 39 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 40 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 41 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 45 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 48 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 50 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 51 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 53 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 54 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 55 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 56 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 60 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 61 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 62 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 65 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 67 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 68 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 71 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 72 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 73 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 74 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 76 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 79 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 80 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 81 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 82 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 83 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 84 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 86 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 88 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 89 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 90 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 92 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 93 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 94 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 97 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 98 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True
timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid 99 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/cifar_nns/ffnnRELU__Point_6_500.pyt --dataset cifar10 --epsilon 0.0032 --is_refinement True


# imgid=71
# while (( $imgid <= 99))
# do
#     timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid $imgid --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/mnist_nns/mnist_relu_9_200.onnx --dataset mnist --epsilon 0.015 --is_refinement True
#     imgid=$((imgid+gap))
# done


# /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 1 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/mnist_nns/mnist_relu_9_200.onnx --dataset mnist --epsilon 0.015 --is_refinement True
# /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 12 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/mnist_nns/mnist_relu_9_200.onnx --dataset mnist --epsilon 0.015 --is_refinement True
# /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 16 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/mnist_nns/mnist_relu_9_200.onnx --dataset mnist --epsilon 0.015 --is_refinement True
# /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 20 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/mnist_nns/mnist_relu_9_200.onnx --dataset mnist --epsilon 0.015 --is_refinement True
# /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_cascade.py --imageid 34 --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/mnist_nns/mnist_relu_9_200.onnx --dataset mnist --epsilon 0.015 --is_refinement True
#Run our SMUPoly 
# imgid=2
# while (( $imgid <= 99))
# do
#     timeout -k 10 12600 /home/zhongyy/Verifier_nn/ERAN/eran_env/bin/python3.6 run_SMUPoly.py --imageid $imgid --netname /home/zhongyy/Verifier_nn/RefineBBPoly/test_nns/mnist_nns/ffnnRELU__Point_6_500.onnx --dataset mnist --epsilon 0.037 --is_refinement True
#     imgid=$((imgid+gap))
# done